CELLRANGER_PATH: /cache/home/mal456/bin/cellranger-7.0.1/ # path to cellranger dir (dont include the binary itself)

# for cellranger multi, which uses a weird toml-like csv config
CMO_GROUPS:
  JUVENILE:
    MULTI_CSV: config/cellranger_config.csv
    FQS: ["data/6417-DJ-1-CMO_GTCGTAAA-AGCCTACT_S2_R1_001.fastq.gz", "data/6417-DJ-1-CMO_GTCGTAAA-AGCCTACT_S2_R2_001.fastq.gz", "data/6417-DJ-1-GEX_TGCAATGT-TTCGACAA_S1_R1_001.fastq.gz", "data/6417-DJ-1-GEX_TGCAATGT-TTCGACAA_S1_R2_001.fastq.gz"]
  ADULT_9646_1:
    MULTI_CSV: config/cellranger_config.9646-DJ-1.csv
    FQS: [data/9646-DJ-1-3CMO_S16_R1_001.fastq.gz, data/9646-DJ-1-GEX_S17_R2_001.fastq.gz, data/9646-DJ-1-3CMO_S16_R2_001.fastq.gz, data/9646-DJ-1-GEX_S17_R1_001.fastq.gz]
  ADULT_9646_2:
    MULTI_CSV: config/cellranger_config.9646-DJ-2.csv
    FQS: [data/9646-DJ-2-3CMO_S18_R1_001.fastq.gz, data/9646-DJ-2-3CMO_S18_R2_001.fastq.gz, data/9646-DJ-2-GEX_S19_R1_001.fastq.gz, data/9646-DJ-2-GEX_S19_R2_001.fastq.gz]
  ADULT_9682_1:
    MULTI_CSV: config/cellranger_config.9682-DJ-1.csv
    FQS: [data/9682-DJ-1-3CMO_S20_R1_001.fastq.gz, data/9682-DJ-1-3CMO_S20_R2_001.fastq.gz, data/9682-DJ-1-GEX_S21_R1_001.fastq.gz, data/9682-DJ-1-GEX_S21_R2_001.fastq.gz]
  ADULT_9682_2:
    MULTI_CSV: config/cellranger_config.9682-DJ-2.csv
    FQS: [data/9682-DJ-2-3CMO_S22_R1_001.fastq.gz, data/9682-DJ-2-3CMO_S22_R2_001.fastq.gz, data/9682-DJ-2-GEX_S23_R1_001.fastq.gz, data/9682-DJ-2-GEX_S23_R2_001.fastq.gz]

# # for cellranger count, which uses an even more inflexible file-name based scheme
# ADULT_CELLRANGER_FQ_DIR: /projectsp/f_cee53_1/ellison_lab/matt/JainLabSingleCell23/data
# ADULT_CELLRANGER_SAMPLES:
#   adult1: 8721-DJ-1-GEX_ACCAGACAAC-CCTAGTTCCT
#   adult2: 8721-DJ-2-GEX_GAGAGGATAT-CCCATTTCAA
#   adult3: 8721-DJ-3-GEX_ATGACGTCGC-ATCCTGACCT
#   adult4: 8721-DJ-4-GEX_CCCGTTCTCG-CCAATCCGTC


# configuration for each snakemake module used
modules:
  generic_masked_genome_plus_tes:
    GENOME_FASTA: "file:///projectsp/genetics/ellison_lab/matt/JainLabResources/refdata-gex-mm10-2020-A/fasta/genome.fa" # example: a genome fasta file (only tested with uncompressed)
    HOST_GTF: "file:///projectsp/genetics/ellison_lab/matt/JainLabResources/refdata-gex-mm10-2020-A/genes/genes.gtf" # example: a gtf file (only tested with uncompressed)
    REPEATMASKER_ARGS: '-e ncbi -no_is -s'
    modules:
      generic_dfam_extract:
        DFAM_CURATED_H5: https://www.dfam.org/releases/Dfam_3.7/families/Dfam_curatedonly.h5.gz
        FAMDB_ARGS: "--curated -ad 'mus musculus'"
        DFAM_CLASSES: [SINE,LINE,LTR,DNA,RC]

